<?xml version="1.0" encoding="utf-8"?><Database Name="arduino" Class="UsuariosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ALLAN;Initial Catalog=arduino;Integrated Security=True" SettingsObjectName="Repositorio.Properties.Settings" SettingsPropertyName="arduinoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.usuarios" Member="usuarios">
    <Type Name="usuario">
      <Column Name="code" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="vencido" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="multas" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>